version: "3"

services:
  ws_flask:
    container_name: ws_flask
    build:
      context: .
      dockerfile: Dockerfile
    image: ws_flask
    environment:
      - API_SERVER=${API_SERVER}
      - LOCAL_PORT=${LOCAL_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: unless-stopped
    ports:
      - "${LOCAL_PORT}:20080"
    volumes:
    - ws_flask_data:/ws_flask
#    entrypoint: ["/bin/sleep", "infinity"]
#    entrypoint:
#      - flask
#      - init-db
    entrypoint:
      - gunicorn
      - --workers=2
      - --threads=4
      - --worker-class=gthread
      - --worker-tmp-dir
      - /dev/shm
      - -b
      - 0.0.0.0:20080
      - -k
      - flask_sockets.worker
      - app:app

volumes:
  ws_flask_data:
    external: true
